# Generated by Django 4.2.16 on 2024-12-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
